global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'blacktop_blackout_api'
    static_configs:
      - targets: ['api:3000']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres:9187']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['redis:9121']

rule_files:
  - 'alert_rules.yml'

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - 'alertmanager:9093'
